name: adver
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.1.0
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2020.4.5.1
  - decorator=4.4.2
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gast=0.2.2
  - glib=2.63.1
  - graphite2=1.3.13
  - graphviz=2.40.1
  - harfbuzz=1.8.8
  - icu=58.2
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jpeg=9b
  - jupyter_client=6.1.2
  - jupyter_core=4.6.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - ncurses=6.2
  - openssl=1.1.1g
  - pango=1.42.4
  - parso=0.6.2
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pixman=0.38.0
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - readline=8.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7

